### ISSUE TITLE
Problem installing autognet

### ISSUE THREAD

**Issue by juandavidgutier** [isabelfulcher/autognet#10]
Hello @isabelfulcher, 

I am new with autognet, and I am trying to install it with this command: "devtools::install_github("isabelfulcher/autognet", ref = "nuterms")". But I get this error message:

collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'autognet'
* removing 'C:/Users/juand/Documents/R/win-library/4.0/autognet'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/juand/AppData/Local/Temp/RtmpI128wn/file2f7029313318/autognet_0.0.2.tar.gz’ had non-zero exit status

I am working in R-4.0.5, and I do not know how to solve this install problem. I would appreciate a lot your cooperation.
